apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator-deployment
  labels:
    app: moderator-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator-microservice
  template:
    metadata:
      labels:
        app: moderator-microservice
    spec:
      containers:
      - name: moderator-microservice
        image: DOCKER_IMAGE
        ports:
        - name: http
          containerPort: 8004
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1