apiVersion: v1
kind: Service
metadata:
  name: moderator-linux-service
  labels:
    app: moderator-microservice
spec:
  type: LoadBalancer
  selector:
    app: moderator-microservice
  ports:
    - port: 8004
      targetPort: 8004